### ISSUE TITLE
Do slides + present to Yarik's lab

### ISSUE THREAD

**Issue by scovitz** [PennLINC/CuBIDS#237]

**Comment by yarikoptic** [comment]
the issue was addressed today ;)

**Comment by yarikoptic** [comment]
were could we find slides btw? ;)

**Comment by scovitz** [comment]
Hi! Thanks for this, and apologies for the delay. It's been a busy couple of weeks for our team. I'll look over this PR and am working on the issues you posted. Additionally, the slides are below: https://docs.google.com/presentation/d/17uMYQpZKXy_TU9vO6liPehjux_5MhntjC0Bs7Ma_nlA/edit#slide=id.g106c97030f5_0_10

Thanks so much for letting me present! Your group is fantastic, and it was a lot of fun to speak about CuBIDS with people who are excited about DataLad, methods development, and  BIDS!
