### ISSUE TITLE
JSONDecodeError when running cubids-validate

### ISSUE THREAD

**Issue by marcjaskir** [PennLINC/CuBIDS#242]
I recently installed CuBIDS and datalad, and checked a BIDS dataset into datalad (called "raw"). Running `cubids-validate raw v0 --sequential` returned:

`(cubids) cubids-validate raw v0 --sequential
  0%|                                                                                                               | 0/130 [00:00<?, ?it/s]ERROR:cubids-cli:Errors returned from validator run, parsing now
  0%|                                                                                                               | 0/130 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/bin/cubids-validate", line 8, in <module>
    sys.exit(cubids_validate())
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/site-packages/cubids/cli.py", line 190, in cubids_validate
    tmp_parse = parse_validator_output(decoded)
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/site-packages/cubids/validator.py", line 91, in parse_validator_output
    data = json.loads(output)
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Here are the steps to reproduce the problem:

conda create -n cubids python=3.8
conda activate cubids
pip install CuBIDS
conda install nodejs
npm install -g bids-validator
conda install -c conda-forge datalad
cubids-validate raw v0 --sequential

**Comment by scovitz** [comment]
Hi @marcjaskir I was able to successfully run validate on this participant, so my guess is one of your jsons (in another participant directory) is in an invalid format. If you run `cubids-add-nifti-info` on your full dataset, CuBIDS should tell you which sidecar (if any) it is unable to parse.

**Comment by marcjaskir** [comment]
Hi @scovitz thanks for the help! Unfortunately, running `cubids-add-nifti-info` on the full dataset didn't return any errors, and I'm still getting the same error when running `cubids-validate`

All of the .nii.gz files in my dataset are symlinked to a .git annex object after being checked into datalad. Could this explain why it's not working on the full dataset?

**Comment by scovitz** [comment]
Hm. Cubic definitely expects data to be checked into datalad/was built to work with datalad datasets. Can you show me a screenshot of the error you get when you run add-nifti-info?

**Comment by marcjaskir** [comment]
![Screen Shot 2022-11-07 at 12 41 00 PM](https://user-images.githubusercontent.com/113548833/200378147-5f87080f-0710-4ae1-accc-c52e77700e5e.png)

**Comment by scovitz** [comment]
Ok this means CuBIDS is successfully able to open an add values to all of your json sidecars. Which version of the bids-validator do you have installed? Additionally, do you have any JSON files in your dataset that aren't sidecars? The validator might be trying to open one of those and failing due to an invalid format.

**Comment by marcjaskir** [comment]
I have bids-validator 1.9.9 installed. No - only .json sidecars are in this dataset. I'll keep trying to work through this issue, thanks for the help!

**Comment by marcjaskir** [comment]
Update - I ran a separate installation of BIDS validator as a singularity image on my initial BIDS dataset, which revealed this error:

`	1: [ERR] Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
		./sub-011706/ses-004909/func/sub-011706_ses-004909_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-011936/ses-005450/func/sub-011936_ses-005450_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-012410/ses-006230/func/sub-012410_ses-006230_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-012835/ses-004779/func/sub-012835_ses-004779_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-013099/ses-004518/func/sub-013099_ses-004518_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-013473/ses-005962/func/sub-013473_ses-005962_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-013550/ses-004739/func/sub-013550_ses-004739_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-013563/ses-004759/func/sub-013563_ses-004759_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-013831/ses-005440/func/sub-013831_ses-005440_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		./sub-013834/ses-004561/func/sub-013834_ses-004561_task-rest_acq-singleband_bold.json
			Evidence: .CogAtlasID should match format "uri"
		... and 198 more files having this issue (Use --verbose to see them all).`

[https://neurostars.org/t/bids-validator-error-code-55-json-schema-validation-error-effectiveechospacing/3704/16](This post) indicated that I just needed to remove the .CogAtlasID field from my task .jsons in the top level of my BIDS directory. Doing so removed this error from my original BIDS dataset (no other errors were indicated)

However, after making the same changes to the dataset checked into datalad, I still get the same `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` error.

**Comment by scovitz** [comment]
As long as your jsons are bids valid you should be ok. It seems like the issue here is that cubids-validate (which wraps the bids validator) isn't telling you on which json it's failing. I can work on fixing that, but can you try running the standalone validator one more time post removing the invalid field?

**Comment by marcjaskir** [comment]
Attached is the output from BIDS validator

[bids_dataset_cubids2.txt](https://github.com/PennLINC/CuBIDS/files/9984374/bids_dataset_cubids2.txt)
