### ISSUE TITLE
`cubids-validate` `--ignore_subject_consistency` can only be True

### ISSUE THREAD

**Issue by tsalo** [PennLINC/CuBIDS#270]
It looks like `--ignore_subject_consistency` has an action of `store_true` and a default of `True`, so it seems like it can't be `False`. Does that sound accurate?

https://github.com/PennLINC/CuBIDS/blob/71a70267db9f69e6591f6fdcf71d93b89bdb68a9/cubids/cli.py#L65-L70

**Comment by mattcieslak** [comment]
I think we should get rid of this argument. The whole point of cubids is to deal with subject inconsistency, so maybe we don't need this at all
