### ISSUE TITLE
cubids validate doesn't produce tsv

### ISSUE THREAD

**Issue by B-Sevchik** [PennLINC/CuBIDS#334]
## Additional details

- CuBIDS version: 1.1.1.dev18+g065444d
- Datalad version: 1.1.3

### What were you trying to do?
run cubids validate to produce validation tsv file

### What did you expect to happen?
expected v0_validation.tsv to be produced in CuBIDS_Test directory

### What actually happened?
no tsv produced & error message in terminal:

## Reproducing the bug
```
cubids validate BIDS_Dataset_DataLad v0 --sequential
```

**Comment by tientong98** [comment]
This was run using the legacy validator, which didn't output any warnings or errors, that's why the validator output was a blank dataframe and wasn't saved to a tsv.

Closing it as it will be fixed after replacing the legacy validator with the schema validator (#336).
